name: newtask
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_polyline_points: ^1.0.0
  fluttertoast: ^8.2.1
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.8
  provider: ^6.0.5
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/frame.png
    - assets/images/frame.png
    - assets/images/1.5x/frame.png
    - assets/images/2.0x/frame.png
    - assets/images/3.0x/frame.png
    - assets/images/4.0x/frame.png
